name: "Dependabot Automerge - Action"

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest

    steps:
      - name: Get result
        run: echo "${{github.event.pull_request.user.login}}"
        
      - name: Get result2
        run: echo "${{github.event}}"
        
      - name: automerge
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{secrets.PERSONAL_TOKEN}}
