name: "Dependabot Automerge - Action"

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest
  
    env:
      AUTHOR: github.event.pull_request.user.login
      
    steps:
      - name: Get result
        run: echo "${{github.event.pull_request.user.login}}"
        
      - name: Get result 2
        run: echo "${{AUTHOR}}"

      - name: automerge
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        uses: actions/github-script@0.2.0
        with:
          script:  |
            github.pullRequests.createReview({
              owner: AUTHOR,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
          github-token: ${{secrets.PERSONAL_TOKEN}}
